# Generated by Django 6.1.1 on 2026-10-10 12:41

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('churras', '0002_prato_foto_prato'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prato',
            options={'ordering': ['-date_prato'], 'verbose_name': 'Prato', 'verbose_name_plural': 'Pratos'},
        ),
        migrations.AlterField(
            model_name='prato',
            name='categoria',
            field=models.CharField(max_length=100, verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='date_prato',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name='Data de Criação'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='funcionario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Funcionário Responsável'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='ingredientes',
            field=models.TextField(verbose_name='Ingredientes'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='modo_preparo',
            field=models.TextField(verbose_name='Modo de Preparo'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='nome_prato',
            field=models.CharField(max_length=100, verbose_name='Nome do Prato'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='publicado',
            field=models.BooleanField(default=False, verbose_name='Publicado'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='rendimento',
            field=models.CharField(max_length=10, verbose_name='Rendimento'),
        ),
        migrations.AlterField(
            model_name='prato',
            name='tempo_preparo',
            field=models.PositiveIntegerField(verbose_name='Tempo de Preparo (min)'),
        ),
    ]
